spring.application.name=asset-map-backend
spring.profiles.default=local

# JPA common
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# JWT common
app.jwt.expiration-ms=86400000
